// src/content.config.ts
import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// 'about' and 'cv' folders are read directly via Astro.glob — not via getCollection.
// Registering them here suppresses the "auto-generated collection" deprecation warning.
const about = defineCollection({ type: 'content', schema: z.object({}).passthrough() });
const cv = defineCollection({ type: 'content', schema: z.object({}).passthrough() });

const profile = defineCollection({
  type: 'data',
  schema: z.object({
    name: z.object({ en: z.string(), vi: z.string() }),
    tagline: z.object({ en: z.string(), vi: z.string() }),
    location: z.string(),
    email: z.string().email(),
    socials: z.object({
      github: z.string().url(),
      linkedin: z.string().url(),
      facebook: z.string().url().optional(),
    }),
    cvFile: z.string(), // path to /public/cv.pdf
    // Achievement highlights shown in the 3D HUD corners + 2D hero stat row.
    // Not derivable from GitHub — authored here, bilingual. accent picks the
    // neon (cyan) vs amber holo treatment.
    highlights: z
      .array(
        z.object({
          value: z.object({ en: z.string(), vi: z.string() }),
          label: z.object({ en: z.string(), vi: z.string() }),
          accent: z.enum(['neon', 'amber']).default('neon'),
        }),
      )
      .default([]),
  }),
});

const experience = defineCollection({
  type: 'content',
  schema: z.object({
    company: z.string(),
    role: z.object({ en: z.string(), vi: z.string() }),
    period: z.object({ start: z.string(), end: z.string().nullable() }),
    logo: z.string().optional(),
    stack: z.array(z.string()),
    order: z.number(),
  }),
});

const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    summary: z.object({ en: z.string(), vi: z.string() }),
    cover: z.string(),
    repo: z.string().url().optional(),
    demo: z.string().url().optional(),
    stack: z.array(z.string()),
    featured: z.boolean().default(false),
    stars: z.number().optional(),
    category: z.enum(['ai-ml', 'backend', 'devops', 'web', 'research']),
    publishedAt: z.date(),
    // Auto-update fields (optional — don't break existing entries):
    // `repoSlug` = "owner/repo" linking the project to live GitHub meta + README.
    // `private` marks repos read via PAT at build time (booking, techleague).
    repoSlug: z.string().optional(),
    private: z.boolean().default(false),
  }),
});

// Auto-generated by scripts/fetch-project-readmes.mjs (prebuild). The glob loader
// returns [] silently when no markdown exists (no repo README carries markers yet),
// avoiding the empty-legacy-collection warning.
const projectReadmes = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/project-readmes' }),
  schema: z.object({
    slug: z.string(),
    sourceRepo: z.string(),
    fetchedAt: z.string(),
  }),
});

const papers = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    authors: z.array(z.string()),
    venue: z.string(),
    year: z.number(),
    pdf: z.string().optional(),
    doi: z.string().optional(),
    award: z.string().optional(), // "🏆 1st Place ALQAC 2023"
  }),
});

const skills = defineCollection({
  type: 'data',
  schema: z.object({
    groups: z.array(z.object({
      category: z.string(),
      items: z.array(z.object({
        name: z.string(),
        level: z.number().min(1).max(5),
        years: z.number().optional(),
        icon: z.string().optional(),
      })),
    })),
  }),
});

export const collections = { profile, experience, projects, projectReadmes, papers, skills, about, cv };
